server:
  port: 9000
spring:
  application:
    name: @artifactId@
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  protocol:
    name: dubbo
    #随机端口
    port: -1
  scan:
    base-packages: com.melelee.dubbo