dubbo:
  application:
    name: @artifactId@
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
    protocol:
    check: false
  consumer:
    check: false
  provider:

